version: '3.9'

services: 
  server: 
    build: .
    ports: 
      - '3000:3000'
  db: 
    image: 'postgres'
    ports: 
      - '4321:5432'
    environment: 
      POSTGRES_PASSWORD: 1234567
      POSTGRES_USER: 'docker'